//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="http://jeffbarnes.net/wcf/samples/client_callback/BeerInventoryService/", ConfigurationName="BeerInventoryService", CallbackContract=typeof(BeerInventoryServiceCallback), SessionMode=System.ServiceModel.SessionMode.Required)]
public interface BeerInventoryService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://jeffbarnes.net/wcf/samples/client_callback/BeerInventoryService/BeerInvent" +
        "oryService/JoinTheParty", ReplyAction="http://jeffbarnes.net/wcf/samples/client_callback/BeerInventoryService/BeerInvent" +
        "oryService/JoinThePartyResponse")]
    int JoinTheParty(string guestName);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://jeffbarnes.net/wcf/samples/client_callback/BeerInventoryService/BeerInvent" +
        "oryService/EstablecerPosicion", ReplyAction="http://jeffbarnes.net/wcf/samples/client_callback/BeerInventoryService/BeerInvent" +
        "oryService/EstablecerPosicionResponse")]
    void EstablecerPosicion(int x, int y);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://jeffbarnes.net/wcf/samples/client_callback/BeerInventoryService/BeerInvent" +
        "oryService/IniciarBola", ReplyAction="http://jeffbarnes.net/wcf/samples/client_callback/BeerInventoryService/BeerInvent" +
        "oryService/IniciarBolaResponse")]
    void IniciarBola();
    
    [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://jeffbarnes.net/wcf/samples/client_callback/BeerInventoryService/BeerInvent" +
        "oryService/MakeBeerRun")]
    void MakeBeerRun(string guestName, int numberOfBeers);
    
    [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://jeffbarnes.net/wcf/samples/client_callback/BeerInventoryService/BeerInvent" +
        "oryService/DrinkBeer")]
    void DrinkBeer(string guestName);
    
    [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://jeffbarnes.net/wcf/samples/client_callback/BeerInventoryService/BeerInvent" +
        "oryService/LeaveTheParty")]
    void LeaveTheParty(string guestName);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public interface BeerInventoryServiceCallback
{
    
    [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://jeffbarnes.net/wcf/samples/client_callback/BeerInventoryService/BeerInvent" +
        "oryService/NotifyGuestJoinedParty")]
    void NotifyGuestJoinedParty(string guestName);
    
    [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://jeffbarnes.net/wcf/samples/client_callback/BeerInventoryService/BeerInvent" +
        "oryService/NotifyCambioPosicion")]
    void NotifyCambioPosicion(int x, int y);
    
    [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://jeffbarnes.net/wcf/samples/client_callback/BeerInventoryService/BeerInvent" +
        "oryService/NotifyBeerInventoryChanged")]
    void NotifyBeerInventoryChanged(string guestName, int numberOfBeers);
    
    [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://jeffbarnes.net/wcf/samples/client_callback/BeerInventoryService/BeerInvent" +
        "oryService/NotifyGuestLeftParty")]
    void NotifyGuestLeftParty(string guestName);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public interface BeerInventoryServiceChannel : BeerInventoryService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public partial class BeerInventoryServiceClient : System.ServiceModel.DuplexClientBase<BeerInventoryService>, BeerInventoryService
{
    
    public BeerInventoryServiceClient(System.ServiceModel.InstanceContext callbackInstance) : 
            base(callbackInstance)
    {
    }
    
    public BeerInventoryServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
            base(callbackInstance, endpointConfigurationName)
    {
    }
    
    public BeerInventoryServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
            base(callbackInstance, endpointConfigurationName, remoteAddress)
    {
    }
    
    public BeerInventoryServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(callbackInstance, endpointConfigurationName, remoteAddress)
    {
    }
    
    public BeerInventoryServiceClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(callbackInstance, binding, remoteAddress)
    {
    }
    
    public int JoinTheParty(string guestName)
    {
        return base.Channel.JoinTheParty(guestName);
    }
    
    public void EstablecerPosicion(int x, int y)
    {
        base.Channel.EstablecerPosicion(x, y);
    }
    
    public void IniciarBola()
    {
        base.Channel.IniciarBola();
    }
    
    public void MakeBeerRun(string guestName, int numberOfBeers)
    {
        base.Channel.MakeBeerRun(guestName, numberOfBeers);
    }
    
    public void DrinkBeer(string guestName)
    {
        base.Channel.DrinkBeer(guestName);
    }
    
    public void LeaveTheParty(string guestName)
    {
        base.Channel.LeaveTheParty(guestName);
    }
}
